### PR TITLE
ENG-83

### PR DESCRIPTION
**Pull request by egh**
https://jira.plos.org/jira/browse/ENG-83

AC
1: 
image
2.
image
3. 
image

If you have a working alm reports setup, I'd try this out. but if not it's probably not worth the trouble. Getting it set up was 99% of the work.

### CODE REVIEW

**Comment by benjaminkreen** [comment]
any thoughts on the blocking ticket https://jira.plos.org/jira/browse/ALM-1099 ? Seems like this would will just languish in the verification column.

**Comment by egh** [comment]
lol. well we could just copy over those logos to the prod machine :shrug:

**Comment by benjaminkreen** [comment]
yep, thats what i was thinking

**Comment by egh** [comment]
If ALM-1099 is not a blocker, what do you think about this PR?

**Review by benjaminkreen — APPROVED** [review]
super good! 💯

**Pull request merged**
